### ISSUE TITLE
Support for in-path url parameters

### ISSUE THREAD

**Issue by sokqa** [danleonard-nj/swagger-gen#10]
Hi! Thanks for this awesome project, which spared me days if not weeks. I'm wondering if support for [path url parameters](https://swagger.io/docs/specification/describing-parameters/#path-parameters) is (or will be) available? I used the `swagger_metadata` decorator and the `query_params` parameter in it, but the parameters I added don't show up in `swagger.json`. And even if they did, I'm not sure if they would be path parameters or query parameters.
Thanks.

**Comment by danleonard-nj** [comment]
Hey @zslim thanks for the heads up, check out v0.1.2 - should be fixed :)

**Comment by sokqa** [comment]
Wow that was fast, thank you! Just a note: I still need to add `@swagger_metadata(query_params=[])` for path parameters to show up. Thanks again.

**Comment by sokqa** [comment]
Also, type notations like `/resource/<int:id>` are not handled.
